<div style="text-align: center;">
  <font size="5"> 線形代数(Linear algebra) scipy版 </font>
</div>
<div style="text-align: right;">
  <font size="3"> cc by Shigeto R. Nishitani, 2017-2018 </font>
</div>
* file: /Users/bob/python/doing_math_with_python/linear_algebra_scipy.ipynb

pythonでの線形代数のlibraryはいくつもあるように見える．
混乱しがちなんで，それをいくつか分類してみた．
間違ってたら教えて．

* numpy.linalg
* scipy.linalg
* sympy

scipyはnumpyのwrapperっぽい．[NumpyとScipy](https://www.eidos.ic.i.u-tokyo.ac.jp/~tau/lecture/computational_physics/slide/numpy.pdf)によると，
1. NumPy ⊂ SciPy ということのようだ
1. numpy で提供されている機能はそのまま, scipy でも提供されている
1. なので scipy だけで押し通しても良さそうだが, 世の中の説明は numpy が主流なので, それに合わせて, 基本は numpy, scipy だけで 提供されている機能は scipy を使う

と明言されている．これが一番混乱がなさそう．

sympyは代数計算向きなんで，表記がだいぶ違う．[別章](./linear_algebra_sympy.ipynb)として提供．




<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#出力精度の制御" data-toc-modified-id="出力精度の制御-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>出力精度の制御</a></span></li><li><span><a href="#行列，ベクトルの生成" data-toc-modified-id="行列，ベクトルの生成-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>行列，ベクトルの生成</a></span></li><li><span><a href="#行列の形状(shape)" data-toc-modified-id="行列の形状(shape)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>行列の形状(shape)</a></span><ul class="toc-item"><li><span><a href="#ゼロ行列，単位行列" data-toc-modified-id="ゼロ行列，単位行列-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>ゼロ行列，単位行列</a></span></li><li><span><a href="#転置(transpose)" data-toc-modified-id="転置(transpose)-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>転置(transpose)</a></span></li></ul></li><li><span><a href="#行列，ベクトルの演算" data-toc-modified-id="行列，ベクトルの演算-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>行列，ベクトルの演算</a></span><ul class="toc-item"><li><span><a href="#ドット積" data-toc-modified-id="ドット積-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>ドット積</a></span></li><li><span><a href="#外積，outer,-cross" data-toc-modified-id="外積，outer,-cross-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>外積，outer, cross</a></span></li><li><span><a href="#スカラー三重積" data-toc-modified-id="スカラー三重積-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>スカラー三重積</a></span></li></ul></li><li><span><a href="#行列要素のとりだし，追加" data-toc-modified-id="行列要素のとりだし，追加-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>行列要素のとりだし，追加</a></span></li><li><span><a href="#掃き出し,-LU分解" data-toc-modified-id="掃き出し,-LU分解-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>掃き出し, LU分解</a></span><ul class="toc-item"><li><span><a href="#階数" data-toc-modified-id="階数-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>階数</a></span></li></ul></li><li><span><a href="#逆行列" data-toc-modified-id="逆行列-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>逆行列</a></span><ul class="toc-item"><li><span><a href="#行列式" data-toc-modified-id="行列式-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>行列式</a></span></li><li><span><a href="#連立方程式の解" data-toc-modified-id="連立方程式の解-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>連立方程式の解</a></span></li><li><span><a href="#課題" data-toc-modified-id="課題-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>課題</a></span></li></ul></li><li><span><a href="#固有値，固有ベクトル" data-toc-modified-id="固有値，固有ベクトル-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>固有値，固有ベクトル</a></span><ul class="toc-item"><li><span><a href="#ベクトルの規格化" data-toc-modified-id="ベクトルの規格化-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>ベクトルの規格化</a></span></li><li><span><a href="#対角化" data-toc-modified-id="対角化-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>対角化</a></span></li><li><span><a href="#課題" data-toc-modified-id="課題-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>課題</a></span></li></ul></li></ul></div>

# 出力精度の制御

行列の出力はとても醜くなる場合がある．
ほぼ0なのにとか，次元が増えてとかで．そのときこいつが役立つ．

In [3]:
import numpy as np
from pprint import pprint
import scipy.linalg as linalg

a = np.array([[2,5], [4,1]])
l,P = np.linalg.eig(a)
pprint(l)
pprint(P)

np.set_printoptions(precision=3, suppress=True)

pprint(l)
pprint(P)

array([ 6., -3.])
array([[ 0.78086881, -0.70710678],
       [ 0.62469505,  0.70710678]])
array([ 6., -3.])
array([[ 0.781, -0.707],
       [ 0.625,  0.707]])


# 行列，ベクトルの生成

In [4]:
import numpy as np
import scipy as sp
list_a = [1,2]
list_b = [3,4]
np_a = np.array([list_a, list_b])
print(np_a)

sp_a = sp.array([list_a, list_b])
print(sp_a)

np_m = np.matrix([list_a, list_b])
print(np_m)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


<ipython-input-4-6b5cbc232797>:8: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  sp_a = sp.array([list_a, list_b])


In [5]:
list_a = [1,2]

np_a_1 = np.array(list_a)
print(np_a_1)

np_v = np.array([list_a])
print(np_v)
# np.vectorはない．

[1 2]
[[1 2]]


# 行列の形状(shape)

In [6]:
print(np_v.shape)
print(np_m.shape)

(1, 2)
(2, 2)


## ゼロ行列，単位行列

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 転置(transpose)

In [10]:
print(np_a.transpose())
print(sp_a.transpose())
print(np_m.transpose())

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [11]:
np_v.transpose()

array([[1],
       [2]])

In [12]:
print(np_v.shape)
print(np_v.transpose().shape)

(1, 2)
(2, 1)


# 行列，ベクトルの演算
## ドット積

$$
\left[
\begin {array}{cc} 
1&2\\
3&4
\end {array} \right]
\left[
\begin {array}{c} 
1\\
2
\end {array} \right]
$$

を計算したいときは，

In [13]:
np.dot(np_a,np.transpose(np_v))

array([[ 5],
       [11]])

In [14]:
np_v.dot(np_a)

array([[ 7, 10]])

これだと，
$$
\left[
\begin {array}{cc} 
1&2
\end {array} \right]
\left[
\begin {array}{cc} 
1&2\\
3&4
\end {array} \right]
$$

を計算することになる．

ベクトルの距離
$$
\left[
\begin {array}{cc} 
1&2
\end {array} \right]
\left[
\begin {array}{cc} 
1\\
2
\end {array} \right]
$$
は

In [15]:
np_v.dot(np_v)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

ではダメで，

In [16]:
np_v.dot(np_v.transpose())

array([[5]])

In [17]:
np_v.transpose().dot(np_v)

array([[1, 2],
       [2, 4]])

と順番を間違うと悲惨．単に長さだけなら$||v||$の代わりにnp.linalg.norm(v)も使える．

In [18]:
np.linalg.norm(np_v)**2

5.000000000000001

ただし，normなんでそのほかの指数も指定できる．

In [19]:
np.linalg.norm(np_v,1)**2

4.0

**補足：** Python 3.5 以降では，`np.dot()` や `.dot()` メソッドの代わりに **`@` 演算子** を使用して，行列演算をよりシンプルに書けます．transposeもnp_v.Tなどと書けます．

In [42]:
# In [13] の書き換え（np.dot(np_a, np.transpose(np_v)) と同じ）
print(np_a @ np_v.T)

# In [14] の書き換え（np_v.dot(np_a) と同じ）
print(np_v @ np_a)

# In [16] の書き換え（np_v.dot(np_v.transpose()) と同じ）
print(np_v @ np_v.T)

# In [17] の書き換え（np_v.transpose().dot(np_v) と同じ）
print(np_v.T @ np_v)

[[ 5]
 [11]]
[[ 7 10]]
[[5]]
[[1 2]
 [2 4]]


## 外積，outer, cross

In [20]:
v1 = np.array([1,1,3])
v2 = np.array([1,2,-1])

In [21]:
np.outer(v1,v2)

array([[ 1,  2, -1],
       [ 1,  2, -1],
       [ 3,  6, -3]])

In [22]:
np.cross(v1,v2)

array([-7,  4,  1])

## スカラー三重積

In [23]:
v3 = np.array([-1,2,1])
np.dot(np.cross(v1,v2),v3)

16

# 行列要素のとりだし，追加

In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# i行j列の要素の取り出し
a[1,1]

5

In [25]:
a[:2,1:4]

array([[2, 3],
       [5, 6]])

In [26]:
col_0 = a[:,0]
print(col_0)

[1 4 7]


In [27]:
row_1 = a[1,:]
print(row_1)

[4 5 6]


In [28]:
b = np.array([1,2,3])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

hstackはa,bが同じ次元でないとダメとのお達し．拡大係数行列を手軽に作れるわけではなさそう．column_stackを使うとできた．

In [29]:
np.column_stack((a,b))

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

# 掃き出し, LU分解

In [30]:
import scipy.linalg

a = np.array([[1,-1,-1],[1,-1,1],[1,1,-1]])

P, L, U = scipy.linalg.lu(a)

print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[ 1. -1. -1.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]


In [31]:
b = np.array([1,-1,-1])
ab = np.column_stack((a,b))
P, L, U = scipy.linalg.lu(ab)
print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[ 1. -1. -1.  1.]
 [ 0.  2.  0. -2.]
 [ 0.  0.  2. -2.]]


## 階数

In [32]:
print(a)

print(np.linalg.matrix_rank(a))
print(np.rank(a)) #deprecatedなんでやめろって，
# 関数名とかlibの区分けに統一性がないよね．．．


[[ 1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]]
3


AttributeError: module 'numpy' has no attribute 'rank'

# 逆行列

In [33]:
a = np.array([[1,2],[3,4]])
scipy.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 行列式

In [34]:
c = np.array([[1,1],[1,2]])
print(np.linalg.det(c))

a = np.array([[1,2],[3,4]])
scipy.linalg.det(a)

1.0


-2.0

## 連立方程式の解
逆行列を用いて，連立方程式の解を求めるには次の通り．
例えば，連立方程式が次のような場合，
$$
x - y -z = 1 \\
x - y +z = -1 \\
x + y -z = -1
$$

In [35]:
a=np.array([[1,-1,-1],[1,-1,1],[1,1,-1]])
b = np.array([1,-1,-1])
scipy.linalg.inv(a).dot(b)


array([-1., -1., -1.])

## 課題
次の連立方程式を解け．
$$ 
\left\{
\begin {array}{cl} 
x+y+z&=0\\
ax+by+cz&=0\\
bcx+cay+abz&=(a-b)(b-c)(c-a)
\end {array} \right.
$$


In [36]:
from pprint import pprint
from sympy import *
a,b,c,x,y,z = symbols('a b c x y z')

A = Matrix([[1,1,1],[a,b,c],[b*c,c*a,a*b]])
bb = Matrix([0,0,(a-b)*(b-c)*(c-a)])
print(A)
print(bb)
Ainv = A.inv()
res = Ainv * bb
pprint(simplify(res[0]))
pprint(simplify(res[1]))
pprint(simplify(res[2]))

Matrix([[1, 1, 1], [a, b, c], [b*c, a*c, a*b]])
Matrix([[0], [0], [(-a + c)*(a - b)*(b - c)]])
-b + c
a - c
-a + b


# 固有値，固有ベクトル

In [37]:
a = np.array([[1,1],[0,2]])
l, P = scipy.linalg.eig(a)
print(l)
print(P)

[1.+0.j 2.+0.j]
[[1.    0.707]
 [0.    0.707]]


## ベクトルの規格化

In [38]:
# eigの固有ベクトルは規格化されている
p_norm = np.linalg.norm(P[:,1])
p_norm
# 規格化はこいつをつかって．．．

0.9999999999999999

## 対角化

Pに固有ベクトルが入っているので，対角化は$P^{-1} A P$で

In [39]:
np.dot(np.dot(np.linalg.inv(P),a),P)
#np.dot(np.dot(np.linalg.inv(P),a),P)

array([[1., 0.],
       [0., 2.]])

## 課題
行列
$$
A\, = \, \left[
\begin {array}{ccc} 
2&0&1\\
0&3&0\\
1&0&2
\end {array} \right]
$$

を対角化する変換行列$P$を求め，対角化せよ．

In [40]:
import numpy as np

A = np.array([[2,0,1],[0,3,0],[1,0,2]])
l, P = np.linalg.eig(A)
print(l)
print(P)

np.dot(np.dot(np.linalg.inv(P),A),P)

[3. 1. 3.]
[[ 0.707 -0.707  0.   ]
 [ 0.     0.     1.   ]
 [ 0.707  0.707  0.   ]]


array([[3., 0., 0.],
       [0., 1., 0.],
       [0., 0., 3.]])

In [41]:
import numpy as np
from math import pi

np.linspace(0,2*pi,9)

array([0.   , 0.785, 1.571, 2.356, 3.142, 3.927, 4.712, 5.498, 6.283])